# Generated by Django 4.0.6 on 2022-07-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('modelo', models.CharField(max_length=128)),
                ('cor', models.SmallIntegerField(choices=[(1, 'Preto'), (2, 'Branco'), (3, 'Vermelho'), (4, 'Prata')], default=1)),
            ],
        ),
    ]
