# Generated by Django 4.0.6 on 2022-07-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('veiculos', '0002_marca_veiculo_ativo_veiculo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
