# Generated by Django 4.0.6 on 2022-07-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0003_veiculo_proprietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=70)),
                ('client_adress', models.CharField(max_length=280)),
                ('final_adress', models.CharField(max_length=280)),
                ('distancia', models.SmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carona', to='veiculos.veiculo')),
            ],
        ),
    ]
