# Generated by Django 4.0.6 on 2022-07-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='distancia',
            field=models.FloatField(),
        ),
    ]
